### ISSUE TITLE
File path changing after close and reopen

### ISSUE THREAD

**Issue by nathanaelmoyer** [NoahMoyer/Election-file-saver#16]
If the file path is long enough it seems like it gets set to something else after I close and then open the app again.
Example file path: U:\CLERK\Elections\2022 Election Information\November 8, 2022 Statewide General\Voter History
Before closing the app:
![image](https://user-images.githubusercontent.com/36149055/200574120-b22243a5-118c-4b3c-aa73-c1e1e953345b.png)

After closing and reopening:
![image](https://user-images.githubusercontent.com/36149055/200574198-69deaf35-2ed2-492d-a73b-bcbe3ac99ec8.png)

If I click change network location it opens the original location:
![image](https://user-images.githubusercontent.com/36149055/200574986-6a2a09c7-7d97-4454-9355-6942de1934fa.png)

The Settings file seems to remain accurate:
![image](https://user-images.githubusercontent.com/36149055/200575277-19c17fa0-6e84-40f6-9b61-cecd89370a5b.png)

The main issue is it seems to save to the location that is showing visually in the application so if we forget to confirm the network path before copying files we will potentially be copying them to the incorrect place.

**Comment by NoahMoyer** [comment]
Issue was related to the settings file being a csv so the comma made it look like the field ended. Adding quotes around that field solved the issue.
